name: 'sales_customer_analytics'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
test-paths: ["tests"]

models:
  elementary:
    +schema: "elementary"
  sales_customer_analytics:
    staging:
      +enabled: false
    bronze:
      +schema: bronze
      +materialized: incremental
    silver:
      +schema: silver
      +materialized: view
    gold:
      +schema: gold
      +materialized: table

flags:
  require_explicit_package_overrides_for_builtin_materializations: False
  source_freshness_run_project_hooks: True